"""Offline source adaptation for one fixed-architecture local autoresearch profile.

Parses and hashes source only. It never imports/executes upstream, Torch or a
kernel. Generated scripts require separate operator staging and authorization.
Local SDPA/tokenizer/checkpoint adaptations make this a distinct baseline.
"""
from __future__ import annotations

import ast
import hashlib
import math
from typing import Any, cast

from .research_candidate import validate_candidate_files
from .research_profile import verify_upstream_source

REVISION = 'autoresearch-local-fixed-sdpa-v1'
ALLOWED_PARAMETERS = frozenset({'TOTAL_BATCH_SIZE', 'EMBEDDING_LR', 'UNEMBEDDING_LR', 'MATRIX_LR',
    'SCALAR_LR', 'WEIGHT_DECAY', 'ADAM_BETAS', 'WARMUP_RATIO', 'WARMDOWN_RATIO', 'FINAL_LR_FRAC',
    'DEVICE_BATCH_SIZE'})
# Eleven editable assignments: ten scalar values plus one beta tuple. The
# upstream optimization block has ten assignments; DEVICE_BATCH_SIZE is eleventh.


def _require(value):
    if not value:
        raise ValueError('RESEARCH_TRAINING_ADAPTATION_INVALID')


def _source(raw):
    _require(type(raw) is bytes and len(raw) <= 4 * 1024 * 1024)
    try:
        source = raw.decode('utf-8')
        tree = ast.parse(source)
    except (UnicodeError, SyntaxError, RecursionError, ValueError):
        raise ValueError('RESEARCH_TRAINING_ADAPTATION_INVALID') from None
    return source, tree


def _assignments(source, tree):
    starts = [0]
    for line in source.splitlines(keepends=True):
        starts.append(starts[-1] + len(line))
    values, spans = {}, {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
            if name in ALLOWED_PARAMETERS:
                _require(name not in values and node.end_lineno is not None and node.end_col_offset is not None)
                expression = node.value
                try:
                    value = ast.literal_eval(expression)
                except (ValueError, TypeError):
                    # Original fixed TOTAL_BATCH_SIZE expression is the only allowed expression.
                    _require(name == 'TOTAL_BATCH_SIZE' and ast.dump(expression) == ast.dump(ast.parse('2**19', mode='eval').body))
                    value = 2**19
                values[name] = value
                spans[name] = (starts[expression.lineno - 1] + expression.col_offset,
                               starts[cast(int, expression.end_lineno) - 1] + cast(int, expression.end_col_offset))
    _require(set(values) == ALLOWED_PARAMETERS)
    return values, spans


def _mask(source, spans):
    for name, (begin, end) in sorted(spans.items(), key=lambda row: row[1][0], reverse=True):
        source = source[:begin] + '<' + name + '>' + source[end:]
    return source


def _validate_values(values, microbatch):
    for name, value in values.items():
        if name == 'ADAM_BETAS':
            _require(type(value) is tuple and len(value) == 2 and all(type(x) in {int, float}
                     and math.isfinite(x) and 0 <= x < 1 for x in cast(tuple[Any, ...], value)))
        elif name in {'TOTAL_BATCH_SIZE', 'DEVICE_BATCH_SIZE'}:
            _require(type(value) is int and 1 <= value <= 2**22)
        else:
            _require(type(value) in {int, float} and math.isfinite(value) and 0 <= value <= 10)
            if name in {'WARMUP_RATIO', 'WARMDOWN_RATIO', 'FINAL_LR_FRAC'}:
                _require(value <= 1)
    _require(values['DEVICE_BATCH_SIZE'] in {128, microbatch})
    _require(values['TOTAL_BATCH_SIZE'] % (microbatch * 2048) == 0)


def _nodes(source, tree, names):
    lines = source.splitlines(keepends=True)
    found = {}
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef)) and node.name in names:
            start = min([node.lineno, *[d.lineno for d in node.decorator_list]])
            found[node.name] = ''.join(lines[start - 1:node.end_lineno])
    _require(set(found) == set(names))
    return '\n\n'.join(found[name] for name in names)


def build_training_bundle(upstream_files, candidate_files, *, microbatch=8):
    """Return generated bytes and explicit offline provenance; never stage or run."""
    profile = verify_upstream_source(upstream_files)
    candidate_receipt = validate_candidate_files(upstream_files, candidate_files)
    _require(type(microbatch) is int and 1 <= microbatch <= 128 and 128 % microbatch == 0)
    original, tree = _source(upstream_files['train.py'])
    candidate, candidate_tree = _source(candidate_files['train.py'])
    baseline_values, baseline_spans = _assignments(original, tree)
    candidate_values, candidate_spans = _assignments(candidate, candidate_tree)
    _require(_mask(original, baseline_spans) == _mask(candidate, candidate_spans))
    _validate_values(baseline_values, microbatch)
    _validate_values(candidate_values, microbatch)
    prepare, prepare_tree = _source(upstream_files['prepare.py'])
    architecture = ('import math\nfrom dataclasses import dataclass\nimport torch\nimport torch.nn as nn\n'
        'import torch.nn.functional as F\nfrom agent_factory.research_torch_runtime import SDPAAdapter\n'
        'fa3 = SDPAAdapter(torch)\n\n' + _nodes(original, tree,
            ['GPTConfig', 'norm', 'has_ve', 'apply_rotary_emb', 'CausalSelfAttention', 'MLP', 'Block', 'GPT',
             'adamw_step_fused', 'muon_step_fused', 'MuonAdamW']))
    # Preserve every fixed top-level optimizer constant by copying that pinned section verbatim.
    optimizer_start = original.index('# Optimizer (MuonAdamW, single GPU only)')
    optimizer_end = original.index('# Hyperparameters (edit these directly, no CLI flags needed)')
    architecture = architecture[:architecture.index('@torch.compile')] + original[optimizer_start:optimizer_end]
    data = ('import math\nimport torch\nfrom agent_factory.research_torch_runtime import runtime\n'
        'MAX_SEQ_LEN=2048\nTIME_BUDGET=300\nEVAL_TOKENS=20971520\n'
        'Tokenizer=runtime.tokenizer_class\nget_token_bytes=runtime.get_token_bytes\n_document_batches=runtime.document_batches\n\n'
        + _nodes(prepare, prepare_tree, ['make_dataloader']))
    generated = {'trusted_architecture.py': architecture.encode(), 'trusted_data.py': data.encode()}
    for filename, source, spans in (('train_baseline.py', original, baseline_spans), ('train_candidate.py', candidate, candidate_spans)):
        begin, end = spans['DEVICE_BATCH_SIZE']
        source = source[:begin] + str(microbatch) + source[end:]
        tail = source[source.index('# Hyperparameters (edit these directly, no CLI flags needed)'):source.index('# Final eval')]
        tail = tail.replace('mfu: {mfu:.1f}%', 'mfu-H100-reference: {mfu:.1f}%')
        prefix = ('import gc, math, time\nfrom dataclasses import asdict\n'
            'from agent_factory.research_torch_runtime import initialize, export_model\n'
            f'initialize(mode="train", microbatch={microbatch})\nimport torch\n'
            'from trusted_architecture import GPT,GPTConfig\n'
            'from trusted_data import MAX_SEQ_LEN,TIME_BUDGET,Tokenizer,make_dataloader\n')
        generated[filename] = (prefix + tail + '\nexport_model(model._orig_mod, asdict(config), total_training_time)\n').encode()
    generated['evaluate.py'] = (f'from agent_factory.research_torch_runtime import evaluate_main\nevaluate_main(microbatch={microbatch})\n').encode()
    return {'generatedFiles': generated, 'receipt': {'schema': 1, 'evidenceKind': 'offline_local_training_adaptation',
        'adaptationRevision': REVISION, 'upstreamCommit': profile['commit'],
        'upstreamSourceSha256': profile['sourceSha256'], 'candidateSource': candidate_receipt,
        'generatedSha256': {name: hashlib.sha256(raw).hexdigest() for name, raw in sorted(generated.items())},
        'approvedMicrobatch': microbatch, 'editableParameters': sorted(ALLOWED_PARAMETERS),
        'baselineKind': 'local-adapted-fixed-architecture-sdpa', 'comparableToUpstreamScore': False,
        'protocolDeltas': ['fixed-pytorch-sdpa-attention', 'safe-operator-tokenizer-json',
            'safe-token-bytes-tensors', 'fixed-microbatch', 'checkpoint-export-before-independent-evaluation'],
        'executionVerified': False, 'scientificConclusionVerified': False}}
