import { currencyMicros, usageLedgerState, usageCommitment, ledgerBudgetAmount } from './usageLedgerState.js';
import type { JobDetail } from './models.js';
export function UsageLedgerPanel({ detail }: { detail: JobDetail }) {
  const state = usageLedgerState(detail);
  if (state.kind === 'missing') return <section><h3>令牌与金额账本</h3><p className="list-empty">服务端尚未提供持久化账本；不估算或假定费用为零。</p></section>;
  if (state.kind === 'invalid') return <section><h3>令牌与金额账本</h3><div className="error-message" role="alert">账本归属、固定费率或预留记录无法核对。保留原任务并核对执行状态。</div></section>;
  const { ledger } = state; const c = ledger.commitment;
  const nominal = ledger.pricingBasis === 'operator-nominal-not-invoice';
  const title = nominal ? '令牌与内部预算账本' : '令牌与金额账本';
  const amount = (value: number) => ledgerBudgetAmount(value, ledger);
  const scopeName = { task: '当前任务', ancestor: '祖先任务', root: '共享根任务', user: '用户累计范围' };
  return <section className="usage-ledger" aria-label={`持久化${title}`}><div className="section-heading"><h3>{title}</h3><span className="quiet">服务端持久化记录</span></div>{nominal && <p className="policy-note" role="note">金额栏仅用于内部预留和名义预算记账，不是提供商账单。实际费用未知，账单尚未核实；已确认令牌用量不代表已确认收费。</p>}{!nominal && ledger.zeroTariff && <p className="state-note">已固定的提供商费率为零。此事实不代表已授权付费模型调用；toy 实验与真实模型科研分别验收。</p>}{ledger.hasUnknown && <p className="policy-note">仍有待确认或未知用量；对应令牌与{nominal ? '预算' : '金额'}预留仍占用上限，未按零用量释放。</p>}<dl className="plan-details"><dt>不可变承诺</dt><dd>{c.provider} / {c.model} · {nominal ? '名义预算费率' : '费率'} {c.pricingRevision}</dd><dt>本任务上限</dt><dd>{c.tokenLimit.toLocaleString()} 令牌 · {amount(c.amountMicros)}</dd></dl><div className="ledger-scopes">{ledger.scopes.map(scope => <div key={`${scope.scope}:${scope.id}`} className="ledger-scope"><strong>{scope.scope === 'task' && ledger.rootTaskId === ledger.taskId ? '当前任务（共享根）' : scopeName[scope.scope]}</strong>{(scope.settledTokens + scope.heldTokens > scope.tokenLimit || scope.settledAmountMicros + scope.heldAmountMicros > scope.amountMicrosLimit) && <p className="ledger-overage" role="status">权威用量记录已超过此范围上限；{nominal ? '内部预算记账保留' : '实际结算保留'}，后续尝试仍受服务端准入限制。</p>}<dl><dt>{nominal ? '已记录用量与名义预算' : '已结算'}</dt><dd>{scope.settledTokens.toLocaleString()} 令牌 · {amount(scope.settledAmountMicros)}</dd><dt>仍预留</dt><dd>{scope.heldTokens.toLocaleString()} 令牌 · {amount(scope.heldAmountMicros)}</dd><dt>累计上限</dt><dd>{scope.tokenLimit.toLocaleString()} 令牌 · {amount(scope.amountMicrosLimit)}</dd></dl></div>)}</div><p className="quiet ledger-note">根任务与用户范围包含其他获准任务；以下尝试明细只属于当前任务。每次重试与流式尝试分别计账。</p>{ledger.attempts.length ? <ul className="ledger-attempts">{ledger.attempts.map(attempt => <li key={attempt.id}><div><strong>{({ RESERVED: '已预留，等待用量', UNKNOWN: '用量未知，保留预留', SETTLED: nominal ? '已记录令牌用量与名义预算' : '已按权威用量结算' })[attempt.state]}</strong><span>{attempt.streaming ? '流式尝试' : '普通尝试'} · {attempt.provider} / {attempt.model}</span></div><p>{attempt.state === 'SETTLED' ? `输入 ${attempt.inputTokens!.toLocaleString()} / 输出 ${attempt.outputTokens!.toLocaleString()} 令牌 · ${amount(attempt.chargedAmountMicros!)}` : `预留 ${attempt.reservedTokens.toLocaleString()} 令牌 · ${amount(attempt.reservedAmountMicros)}`}</p><details className="technical-detail"><summary>尝试与用量依据</summary><span>尝试 {attempt.id}</span><span>运行 {attempt.runId}</span><span>承诺 SHA-256 {attempt.commitmentSha256}</span><span>权威用量 SHA-256 {attempt.usageEvidenceSha256 ?? '尚未提供'}</span></details></li>)}</ul> : <p className="list-empty">当前任务没有提供商尝试记录。</p>}<details className="technical-detail"><summary>{nominal ? '固定内部预算与名义费率版本' : '固定预算与费率版本'}</summary><span>根任务 {ledger.rootTaskId}</span><span>{nominal ? '内部预算计量基准' : '币种'} {ledger.currency}</span><span>承诺 SHA-256 {c.sha256}</span><span>费率 SHA-256 {c.pricingSha256}</span><span>绑定 SHA-256 {c.bindingSha256}</span><span>适配器 {c.adapterId}@{c.adapterRevision}</span>{ledger.migration && <span>包含旧方案迁移记录；原方案哈希由服务端保留。</span>}</details></section>;
}

export function UsageCommitmentSummary({ value }: { value?: unknown }) {
  if (value === undefined || value === null) return <p className="quiet ledger-note">本记录尚未提供新账本的固定承诺；不据此推定任何金额或令牌授权。</p>;
  const c = usageCommitment(value);
  if (!c) return <div className="error-message" role="alert">固定令牌与金额承诺无法核对；应保留方案并刷新授权记录。</div>;
  // This exact operator-owned revision declares nominal accounting. Do not
  // infer billing semantics from arbitrary model names or revision substrings.
  const nominal = c.provider === 'opencode-go-development'
    && c.pricingRevision === 'go-development-operator-nominal-2026-10-04-v2';
  const amount = currencyMicros(c.amountMicros, c.currency);
  return <div className="plan-usage-commitment"><h3>{nominal ? '固定令牌与内部预算承诺' : '固定令牌与金额承诺'}</h3>{nominal && <p className="policy-note">此承诺采用内部名义预算，不是提供商账单；实际费用未知，账单尚未核实。</p>}<dl className="plan-details"><dt>本任务上限</dt><dd>{c.tokenLimit.toLocaleString()} 令牌 · {nominal ? `名义预算单位 ${amount.slice(4)}` : amount}</dd><dt>{nominal ? '提供商 / 模型 / 名义预算费率' : '提供商 / 模型 / 固定费率'}</dt><dd>{c.provider} / {c.model} / {c.pricingRevision}</dd><dt>单次尝试预留上限</dt><dd>输入 {c.perAttemptInputTokens.toLocaleString()} / 输出 {c.perAttemptOutputTokens.toLocaleString()} 令牌</dd></dl><p className="quiet ledger-note">每次提供商尝试、重试和流式尝试均受共享预算约束；未知用量保留预留。批准方案不会授权额外付费模型。</p><details className="technical-detail"><summary>{nominal ? '承诺与名义预算费率摘要' : '承诺与固定费率摘要'}</summary><span>承诺 SHA-256 {c.sha256}</span><span>费率 SHA-256 {c.pricingSha256}</span><span>绑定 SHA-256 {c.bindingSha256}</span></details></div>;
}
